github.com:
    users:
        cartsnitch-qa[bot]:
            oauth_token: ghs_kyu7ex7DQ2h0OJjbRtceCVhp5IeQQz3E8Cl3
    oauth_token: ghs_kyu7ex7DQ2h0OJjbRtceCVhp5IeQQz3E8Cl3
    user: cartsnitch-qa[bot]
